name: Deploy

on:
  push:
    branches:
      - master-not-valid
  # schedule:
  #   - cron: "0 0 1 * *"

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          submodules: true

      - name: Use node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.OS }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-

      - name: Install dependencies
        run: yarn

      - name: Generate static files
        run: yarn generate:ci

      - name: Deploy to surge
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'quran-offline.surge.sh'
          project: './dist'
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}

      # - name: Publish
      #   uses: netlify/actions/cli@master
      #   with:
      #     args: deploy --dir=dist --functions=functions
      #   env:
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
      # - name: GitHub Pages Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     personal_token: ${{ secrets.PERSONAL_TOKEN }}
      #     publish_dir: ./dist
